export default (req, res) => {
  throw new Error('Call next() or throw in Catcher')
}
